library_django/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from registration import views as registration_views
from django.contrib.auth.views import LogoutView
from books import views as books_views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),

               ]
urlpatterns += i18n_patterns(path('admin/', admin.site.urls),
                             path('register/', registration_views.UserCreateView.as_view(), name='register'),
                             path('login/', registration_views.LoginView.as_view(), name='login'),
                             path('logout/', LogoutView.as_view(), name='logout'),
                             path('password_forgotten/', registration_views.PasswordForgottenView.as_view(),
                                  name='password_forgotten'),
                             re_path(r'^reset/(?P<user_id>(\d)+)/(?P<token>(\w)+)',
                                     registration_views.ResetPasswordView.as_view(),
                                     name='reset_password'),
                             re_path(r'^book/(?P<book_id>(\d)+)', books_views.BookDetailsView.as_view(),
                                     name='book_details'),
                             path('', books_views.BooksListView.as_view(), name='home'),
                             re_path(r'^reserve/(?P<book_id>(\d)+)', books_views.BookRentView.as_view(),
                                     name='reserve'),
                             re_path(r'^author/(?P<author_id>(\d)+)', books_views.AuthorDetailsView.as_view(),
                                     name='author_details'),
                             path('user/', books_views.MyBooksView.as_view(), name='my_books'),
                             re_path(r'^users/$', books_views.UserFilterView.as_view(), name='users'),
                             path('book_add/', books_views.BookAddView.as_view(), name='book_add'),
                             re_path(r'^book_edit/(?P<book_id>(\d)+)', books_views.BookEditView.as_view(),
                                     name="book_edit"),
                             re_path(r'^book_delete/(?P<book_id>(\d)+)', books_views.BookDeleteView.as_view(),
                                     name="book_delete"),
                             re_path(r'^book_search/$', books_views.BookFilterView.as_view(), name='book_search'),
                             re_path(r'^user/(?P<user_id>(\d)+)', books_views.UserDetailsView.as_view(),
                                     name='user_details'),
                             re_path(r'^return/(?P<bookuser_id>(\d)+)', books_views.BookReturnView.as_view(),
                                     name='book_return'),
                             re_path(r'^extend/(?P<bookuser_id>(\d)+)', books_views.BookExtendView.as_view(),
                                     name='book_extend'),
                             path('validate_username/', registration_views.ValidateUsername.as_view(),
                                  name='validate_username'),
                             path('export/csv/', books_views.BookExportCsv.as_view(), name="book_export_csv"),
                             path('export/xls/', books_views.BookExportXls.as_view(), name="book_export_xls"),

                             )

books/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from books.utils import get_upload_file_hashdir, make_md5

# Create your models here.

LANGUAGES = (
    ('en', _('english')),
    ('pl', _('polish')),
    ('fr', _('french')),
    ('es', _('spanish')),
    ('de', _('german'))
)
RATING = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))

class Author(models.Model):
    first_name = models.CharField(_('First name'), max_length=128)
    last_name = models.CharField(_('Last name'), max_length=128)


    def __str__(self):
        return self.first_name + " " + self.last_name


class Genre(models.Model):
    name = models.CharField(_('Genre'), max_length=64, unique=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(_('Title'), max_length=128)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.TextField(_('Description'), null=True)
    genre = models.ManyToManyField(Genre)
    language = models.CharField(_('Language'), max_length=32, choices=LANGUAGES, null=True)
    store = models.IntegerField(_('Store'), )
    current_store = models.IntegerField(_('Current store'), blank=True, null=True)
    user = models.ManyToManyField(User, through='BookUser')
    md5_cover = models.CharField(max_length=32, blank=True)
    cover = models.ImageField(_('Cover'), upload_to=get_upload_file_hashdir)
    barcode = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.md5 = make_md5(self.cover.file)
        if self.current_store is None:
            self.current_store = self.store
        super(Book, self).save(*args, **kwargs)


class BookUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1024, null=True, blank=True)
    rating = models.IntegerField(choices=RATING, null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_rented = models.BooleanField(default=False)
    rent_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.user} {self.book}'

books/forms.py
import django.forms as forms
import books.models as models
from django.utils.translation import gettext_lazy as _

authors = models.Author.objects.all()
genres = models.Genre.objects.all()


class BookForm(forms.ModelForm):
    author = forms.ModelChoiceField(label=_('Author'), queryset=authors)
    genre = forms.ModelChoiceField(label=_('Genre'), queryset=genres)

    class Meta:
        model = models.Book
        exclude = ['current_store', 'user', 'md5_cover', 'barcode']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'


class GenreFrom(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from books.models import Book, BookUser, Author
import operator
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from books import forms as books_forms
from django.db.models import Q
from books import filters
from books import validators
import csv
import xlwt


# Create your views here.

class BooksListView(View):
    def get(self, request):
        books = sorted(Book.objects.all(), key=operator.attrgetter('title'))
        return render(request, 'books/books_list.html', {'books': books})

    def post(self, request):
        search = request.POST.get('search')
        print(search)
        books = sorted(Book.objects.filter(
            Q(author__first_name__icontains=search) | Q(author__last_name__icontains=search) | Q(
                title__icontains=search)), key=operator.attrgetter('title'))

        return render(request, 'books/books_list.html', {'books': books})


class BookDetailsView(View):
    def get(self, request, book_id):
        book = Book.objects.get(id=book_id)
        user = request.user
        validation = validators.validate_renting(book, user)

        return render(request, 'books/book_details.html', {'book': book,
                                                           'validation': validation})


class BookRentView(LoginRequiredMixin, View):
    def get(self, request, book_id):
        user = request.user
        book = Book.objects.get(id=book_id)
        if validators.validate_renting(book, user):
            BookUser(user=user, book=book, deadline=timezone.now() + timedelta(days=12), is_rented=True).save()
            book.current_store -= 1
            book.save()
            return redirect('/user/')
        else:
            return redirect('/')


class BookReturnView(PermissionRequiredMixin, View):
    permission_required = 'auth.change_book'
    permission_denied_message = _('access denied')

    def get(self, request, bookuser_id):
        bookuser = BookUser.objects.get(id=bookuser_id)
        bookuser.is_rented = False
        bookuser.return_date = timezone.now()
        bookuser.book.current_store += 1
        bookuser.save()
        bookuser.book.save()
        return redirect(f"/user/{bookuser.user.id}")


class BookExtendView(PermissionRequiredMixin, View):
    permission_required = 'auth.change_book'
    permission_denied_message = _('access denied')

    def get(self, request, bookuser_id):
        bookuser = BookUser.objects.get(id=bookuser_id)
        bookuser.deadline += timedelta(days=7)
        bookuser.save()
        return redirect(f"/user/{bookuser.user.id}")


class AuthorDetailsView(View):
    def get(self, request, author_id):
        author = Author.objects.get(id=author_id)
        return render(request, 'books/author_details.html', {'author': author})


class MyBooksView(LoginRequiredMixin, View):
    def get(self, request):
        bookuser_set = BookUser.objects.filter(user=request.user, is_rented=True)
        return render(request, 'books/my_books.html', {'bookuser_set': bookuser_set})


class BookAddView(PermissionRequiredMixin, View):
    permission_required = 'auth.add_book'
    permission_denied_message = _('access denied')

    def get(self, request):
        book_form = books_forms.BookForm()
        author_form = books_forms.AuthorForm()
        genre_form = books_forms.GenreFrom()
        return render(request, 'books/book_add.html', {'book_form': book_form,
                                                       'author_form': author_form,
                                                       'genre_form': genre_form})

    def post(self, request):
        if 'book_btn' in request.POST:
            form = books_forms.BookForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()

        if 'author_btn' in request.POST:
            form = books_forms.AuthorForm(request.POST)
            if form.is_valid():
                form.save()

        if 'genre_btn' in request.POST:
            form = books_forms.GenreFrom(request.POST)
            if form.is_valid():
                form.save()

        return redirect('/book_add/')


class BookEditView(PermissionRequiredMixin, View):
    permission_required = 'auth.change_book'
    permission_denied_message = _('access denied')

    def get(self, request, book_id):
        book = Book.objects.get(id=book_id)
        form = books_forms.BookForm(instance=book)
        return render(request, 'books/book_edit.html', {'form': form,
                                                        'book_id': book_id})

    def post(self, request, book_id):
        book = Book.objects.get(id=book_id)
        form = books_forms.BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect('/')


class BookDeleteView(PermissionRequiredMixin, View):
    permission_required = 'auth.delete_book'
    permission_denied_message = _('access denied')

    def get(self, request, book_id):
        book = Book.objects.get(id=book_id)
        book.delete()
        return redirect('/book_search')


class BookFilterView(PermissionRequiredMixin, View):
    permission_required = 'auth.change_book'
    permission_denied_message = _('access denied')

    def get(self, request):
        book_list = Book.objects.all()
        filter = filters.BookFilter(request.GET, queryset=book_list)
        return render(request, 'books/book_search.html', {'filter': filter})


class UserFilterView(PermissionRequiredMixin, View):
    permission_required = 'auth.change_book'
    permission_denied_message = _('access denied')

    def get(self, request):
        user_list = User.objects.all()
        filter = filters.UserFilter(request.GET, queryset=user_list)
        return render(request, 'books/users.html', {'filter': filter})


class UserDetailsView(View):

    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        return render(request, 'books/user_details.html', {'user': user})


class BookExportCsv(View):
    def get(self, request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="books.csv"'
        writer = csv.writer(response)
        writer.writerow(['Title', 'Author', 'Description', 'Language'])
        books = Book.objects.all()
        for book in books:
            writer.writerow([book.title, book.author, book.description, book.language])
        return response


class BookExportXls(View):
    def get(self, request):
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="books.xls"'

        workbook = xlwt.Workbook(encoding='utf-8')
        worksheet = workbook.add_sheet('Books')

        """header"""
        row_num = 0
        header_style = xlwt.XFStyle()
        header_style.font.bold = True
        columns = ['Title', 'Author', 'Description', 'Language']
        for col_num in range(len(columns)):
            worksheet.write(row_num, col_num, columns[col_num], header_style)

        """body"""
        body_style = xlwt.XFStyle()
        rows = Book.objects.all()
        for row in rows:
            row_num += 1
            for col_num in range(len(columns)):
                value = ""
                if col_num == 0:
                    value = row.title
                elif col_num == 1:
                    value = f"{row.author.first_name} {row.author.last_name}"
                elif col_num == 2:
                    value = row.description
                elif col_num == 3:
                    value = row.language
                worksheet.write(row_num, col_num, value, body_style)
        workbook.save(response)
        return response

books/templates/books/author_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>{{ author }}</title>{% endblock %}

{% block content %}
    <div align="left">
        <table class="table table-striped">
            <tbody>
            {% for book in author.book_set.all %}
                <tr>
                    <td><img src="{{ book.cover.url }}"></td>
                    <td><a class="nav-link" style="color: #373B43" href="/book/{{ book.id }}">{{ book }}</a></td>
                    <td>{% if book.current_store is 0 %}
                    <img src="{% static 'registration/not.png' %}" width="20" height="20"/>
                {% endif %} </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

books/templates/books/book_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}<title>{% blocktrans %}Add{% endblocktrans %}</title>{% endblock %}


    {% block forms %}
<div class="col-8" style="margin: 5px">
        <div style="float:left;width:50%;margin-right: 30px">
            <form action="{% url 'book_add' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ book_form|crispy }}
                <button type="submit" class="btn btn-dark btn-sm" name="book_btn">{% blocktrans %}Add book{% endblocktrans %}</button>
            </form>
        </div>
        <div style="float:left;width:30%;margin-right: 10px">
            <form action="
        {% url 'book_add' %}" method="post">
                {% csrf_token %}
                {{ author_form|crispy }}
                <button type="submit" class="btn btn-dark btn-sm" name="author_btn">{% blocktrans %}Add author{% endblocktrans %}</button>
            </form>
        </div>
        <div style="float:left;width:30%">
            <form action="{% url 'book_add' %}" method="post">
                {% csrf_token %}
                {{ genre_form|crispy }}
                <button type="submit" class="btn btn-dark btn-sm" name="genre_btn">{% blocktrans %}Add genre{% endblocktrans %}</button>
            </form>
        </div>
       </div>
    {% endblock %}

books/templates/books/book_details.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}<title>{{ book }}</title>{% endblock %}

{% block content %}
    <div align="left">
        <table class="table">
            <tbody>
            <tr>
                <td><img src="{{ book.cover.url }}" width="200" height="200"></td>
                <td><h1>{{ book }}<img src="{% static 'books/rating-4.png' %}" width="150" height="100"/></h1>
                    <p>{{ book.author }}</p><span>{{ book.description }}</span></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div align="right" style="margin: 5px">
        {% if validation %}
            <a href="/reserve/{{ book.id }}" class="btn btn-dark btn-sm" role="button" aria-pressed="true">{% blocktrans %}Rent this
                book{% endblocktrans %}</a>
        {% else %}
            <button type="button" class="btn btn-dark btn-sm" disabled>{% blocktrans %}Rent this book{% endblocktrans %}</button>
        {% endif %}
        {% if perms.auth.edit_book %}
            <a href="/book_edit/{{ book.id }}" class="btn btn-dark btn-sm" role="button" aria-pressed="true">{% blocktrans %}Edit{% endblocktrans %}</a>
        {% endif %}
        {% if perms.auth.delete_book %}
            <button onclick="confiramtion()" type="button" class="btn btn-dark btn-sm" style="color: red"
                    role="button" aria-pressed="true">
                {% blocktrans %}Delete{% endblocktrans %}
            </button>
            </div>
        {% endif %}
    <script>
        function confiramtion() {
            var con = confirm("Are you sure you want to delete this book?");
            if (con === true) {
                window.location.href = "/book_delete/{{ book.id }}";
            }

        }
    </script>
{% endblock %}

books/templates/books/book_edit.html
{% extends 'base.html' %}
{% block title %}<title>Login</title>{% endblock %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block forms %}
    <div class="col-3" style="margin-top: 50px">
        <form action="{% url 'book_edit' book_id=book_id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-dark btn-sm">Save</button>
        </form>
    </div>
{% endblock %}

books/templates/books/book_search.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}<title>{% blocktrans %}Books{% endblocktrans %}</title>{% endblock %}
{% load crispy_forms_tags %}


{% block content %}
    <div>
        <form action="" method="get">
            <div class="form-row" style="margin-left: 10px; margin-top: 10px;">
                <div style="margin-right: 5px;">
                    {{ filter.form.title|as_crispy_field }}
                </div>
                <div style="margin-right: 5px;">
                    {{ filter.form.author|as_crispy_field }}
                </div>
                <div style="margin-right: 5px;">
                    {{ filter.form.language|as_crispy_field }}
                </div>
                <div style="margin-right: 5px;">
                    {{ filter.form.genre|as_crispy_field }}
                </div>
                <div style="margin-right: 5px; width: 10%">
                    {{ filter.form.store|as_crispy_field }}
                </div>
                <div style="margin-right: 5px; width: 10%">
                    {{ filter.form.current_store|as_crispy_field }}
                </div>
                <div style="margin-right: 5px; width:13%">
                    {{ filter.form.bookuser__is_rented|as_crispy_field }}
                </div>
            </div>

            <div style="margin: 10px;">
                <button type="submit" class="btn btn-dark btn-sm">{% blocktrans %}Filtr{% endblocktrans %}</button>
            </div>
            <div style="margin: 10px;">
                <a href="/export/csv" class="btn btn-dark btn-sm" role="button" aria-pressed="true">{% blocktrans %}Export all to CSV
                    file{% endblocktrans %}</a>
                <a href="/export/xls" class="btn btn-dark btn-sm" role="button" aria-pressed="true">{% blocktrans %}Export all to XLS
                    file{% endblocktrans %}</a>
            </div>
        </form>

    </div>
    <div>
        <table class="table table-borderedtable">
            <thead>
            <tr>
                <th>{% blocktrans %}Title{% endblocktrans %}</th>
                <th>{% blocktrans %}Author{% endblocktrans %}</th>
                <th>{% blocktrans %}Language{% endblocktrans %}</th>
                <th>{% blocktrans %}Store{% endblocktrans %}</th>
                <th>{% blocktrans %}Barcode{% endblocktrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for book in filter.qs %}
                <tr>
                    <td><a style="color: #373B43" href="/book/{{ book.id }}">{{ book }}</a></td>
                    <td><a style="color: #373B43"
                           href="/author/{{ book.author.id }}">{{ book.author }}</a></td>
                    <td style="color: #373B43">{{ book.language }}</td>
                    <td style="color: #373B43">{{ book.current_store }}/{{ book.store }}</td>
                    <td style="color: #373B43">{{ book.barcode }}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

books/templates/books/books_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}<title>{% blocktrans %}Books{% endblocktrans %}</title>{% endblock %}

{% block content %}
    <div align="left">
        <table class="table table-striped">
            <tbody>

            {% for book in books %}
                <tr>
                    <td><img src="{{ book.cover.url }}"></td>
                    <td><a class="nav-link" style="color: #373B43" href="/book/{{ book.id }}">{{ book }}</a></td>
                    <td><a class="nav-link" style="color: #373B43"
                           href="/author/{{ book.author.id }}">{{ book.author }}</a></td>
                    <td>{% if book.current_store is 0 %}
                        <p style="color:red;">{{ book.current_store }}/{{ book.store }}</p>
                    {% endif %}
                        {% if book.current_store is not 0 %}
                            <p>{{ book.current_store }}/{{ book.store }}</p>
                        {% endif %}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

books/templates/books/my_books.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}<title>{% blocktrans %}My books{% endblocktrans %}</title>{% endblock %}

{% block content %}
    <div align="left">
        <table class="table table-striped">
            <tbody>
            {% for bookuser in bookuser_set %}
                <tr>
                    <td><img src="{{ bookuser.book.cover.url }}"></td>
                    <td><a class="nav-link" style="color: #373B43" href="/book/{{ bookuser.book.id }}">{{ bookuser.book }}</a></td>
                    <td><p class="nav-link">{{ bookuser.deadline.date }}</p></td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

books/templates/books/user_details.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}<title>{{ user }}</title>{% endblock %}

{% block content %}
    <div style="margin: 5px">
        <h1>{{ user.first_name }} {{ user.last_name }}</h1>
        <p>email: {{ user.username }}</p>

        <table class="table table-borderedtable">
            <thead>
            <tr>
                <th>{% blocktrans %}Title{% endblocktrans %}</th>
                <th>{% blocktrans %}Author{% endblocktrans %}</th>
                <th>{% blocktrans %}Rent Date{% endblocktrans %}</th>
                <th>{% blocktrans %}Deadline{% endblocktrans %}</th>
                <th>{% blocktrans %}Return Date{% endblocktrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for bookuser in user.bookuser_set.all %}
                <tr>
                <td>{{ bookuser.book.title }}</td>
                <td>{{ bookuser.book.author }}</td>
                <td>{{ bookuser.rent_date }}</td>
                <td>{{ bookuser.deadline }}</td>
                <td>{{ bookuser.return_date }}</td>
                {% if bookuser.is_rented %}
                    <td><a href="/return/{{ bookuser.id }}/" class="btn btn-dark btn-sm" role="button" aria-pressed="true">{% blocktrans %}Return{% endblocktrans %}</a>
                    </td>
                {% else %}
                    <td>
                <button type="button" class="btn btn-dark btn-sm" disabled>{% blocktrans %}Return{% endblocktrans %}</button>
                    </td>
                {% endif %}
                {% if bookuser.is_rented %}
                    <td><a href="/extend/{{ bookuser.id }}/" class="btn btn-dark btn-sm" role="button" aria-pressed="true">{% blocktrans %}Extend{% endblocktrans %}</a>
                    </td>
                {% endif %}
                {% if not bookuser.is_rented %}
                    <td>
                <button type="button" class="btn btn-dark btn-sm" disabled>{% blocktrans %}Extend{% endblocktrans %}</button>
                    </td>
                {% endif %}
            {%   endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

books/templates/books/users.html
{% extends 'base.html' %}
{% block title %}<title>Users</title>{% endblock %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}
    <form action="" method="get">
        <div class="form-row" style="margin-left: 10px; margin-top: 10px;">
            <div style="margin-right: 5px;">
                {{ filter.form.username|as_crispy_field }}
            </div>
            <div style="margin-right: 5px;">
                {{ filter.form.first_name|as_crispy_field }}
            </div>
            <div style="margin-right: 5px;">
                {{ filter.form.last_name|as_crispy_field }}
            </div>
            <div style="margin-right: 5px;">
                {{ filter.form.book__title|as_crispy_field }}
            </div>

            <div style="margin-right: 5px;">
                {{ filter.form.bookuser__is_rented|as_crispy_field }}
            </div>

        </div>
        </div>
        <div style="margin: 10px;">
            <button type="submit" class="btn btn-dark btn-sm">{% blocktrans %}Filtr{% endblocktrans %}</button>
        </div>
    </form>
    <ul>
        {% for user in filter.qs %}
            <li><a class="nav-link" style="color: #373B43"
                   href="/user/{{ user.id }}">{{ user }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}